set PATH "@KDE_INSTALL_FULL_BINDIR@:$PATH"

# LD_LIBRARY_PATH only needed if you are building without rpath
# set --path  LD_LIBRARY_PATH @KDE_INSTALL_FULL_LIBDIR@ $LD_LIBRARY_PATH

if set -q XDG_DATA_DIRS
    set XDG_DATA_DIRS "/usr/local/share/:/usr/share/"
end
set XDG_DATA_DIRS "@KDE_INSTALL_FULL_DATADIR@:$XDG_DATA_DIRS"

if set -q XDG_CONFIG_DIRS
    set XDG_CONFIG_DIRS "/etc/xdg"
end
set XDG_CONFIG_DIRS "@KDE_INSTALL_FULL_CONFDIR@:XDG_CONFIG_DIRS"

set QT_PLUGIN_PATH "@KDE_INSTALL_FULL_QTPLUGINDIR@:$QT_PLUGIN_PATH"
set QML2_IMPORT_PATH "@KDE_INSTALL_FULL_QMLDIR@:$QML2_IMPORT_PATH"

set QT_QUICK_CONTROLS_STYLE_PATH "@KDE_INSTALL_FULL_QMLDIR@/QtQuick/Controls.2/:$QT_QUICK_CONTROLS_STYLE_PATH"
